package ca.dal.treefactor.model;

public enum CodeElementType {
    CLASS_DECLARATION,
    METHOD_DECLARATION,
    FIELD_DECLARATION,
    CONSTRUCTOR_DECLARATION,
    ENUM_DECLARATION,
    INTERFACE_DECLARATION,
    PARAMETER_DECLARATION,
    VARIABLE_DECLARATION,
    COMMENT,
    IMPORT_DECLARATION,
    PACKAGE_DECLARATION,
    ANNOTATION_TYPE_DECLARATION
}