name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev  # Triggers the action on push to main or dev branches

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

#      - name: Install dependencies
#        run: sudo apt-get update && sudo apt-get install -y build-essential gcc

      - name: Run the setup-script
        run: |
          chmod +x ./setup_treefactor.sh
          ./setup_treefactor.sh

      - name: Build with Maven
        run: mvn clean package

      - name: Move project to deployment directory
        run: |
          mkdir -p $HOME/Treefactor
          cp -r ./* $HOME/Treefactor

