name: Code Quality Workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download DesigniteJava
        run: |
          mkdir -p code_quality
          wget -O code_quality/DesigniteJava.jar https://www.designite-tools.com/assets/DesigniteJava.jar
          ls -l code_quality/DesigniteJava.jar
          file code_quality/DesigniteJava.jar

      - name: Create CSV output directory
        run: mkdir -p ./smells

      - name: Run Java JAR file
        run: |
          java -jar code_quality/DesigniteJava.jar -i ./src/ -o smells -d
          echo "Generated files:"
          ls -la smells/
          rm code_quality/DesigniteJava.jar

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r ./code_quality/requirements.txt
          pip install csv2md requests

      - name: Open Issues
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Owner: $GITHUB_REPOSITORY_OWNER"
          echo "PAT exists: ${{ secrets.PAT != '' }}"
          python ./code_quality/create_issue.py ${{ github.sha }}