name: Test Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      #- name: Install gcc
      #  run: sudo apt-get update && sudo apt-get install -y build-essential gcc

      - name: Setup tree-sitter
        run: |
          chmod +x ./setup_treefactor.sh
          ./setup_treefactor.sh
      #    ls -la src/main/resources/native/linux/
      #    ls -la .

      - name: Build with Maven
        run: |
          export MAVEN_OPTS="--enable-native-access=ALL-UNNAMED -Djava.library.path=.:src/main/resources/native/linux"
          mvn clean package

      - name: Run Tests
        run: |
          export MAVEN_OPTS="--enable-native-access=ALL-UNNAMED -Djava.library.path=.:src/main/resources/native/linux"
          mvn -B test