name: Test Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
       
      - name: Setup tree-sitter
        run: |
          chmod +x ./setup_treefactor.sh
          ./setup_treefactor.sh
          chmod +x ./libtree-sitter.so 
          ls -la src/main/resources/native/linux/
          ls -la .
          pwd

      - name: ExportLibraryPath
        run: |  
          export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          pwd

      - name: Run Tests
        run: |
          pwd
          mvn test
