name: Test Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc

      - name: Run setup script
        run: |
          chmod +x ./setup_treefactor.sh
          ./setup_treefactor.sh

      - name: Run Tests with Maven
        run: mvn -B test

      - name: Generate Test Report
        if: always()
        run: |
          echo "Test Results:"
          find target/surefire-reports -name "TEST-*.xml" -exec cat {} \;