name: Test Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      #- name: Install gcc
      #  run: sudo apt-get update && sudo apt-get install -y build-essential gcc

      - name: Setup tree-sitter
        run: |
          chmod +x ./setup_treefactor.sh
          ./setup_treefactor.sh
          chmod +x ./libtree-sitter.so 
          ls -la src/main/resources/native/linux/
          ls -la .

      - name: ExportLibraryPath
        run: |  
          export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Run Tests
        run: |
          mvn test